name       : python-helpdev
version    : 0.7.1
release    : 1
source     :
    - https://gitlab.com/dpizetta/helpdev/-/archive/v0.7.1/helpdev-v0.7.1.tar.bz2 : b52f83d6d3935500da42b434747569660d526cd36e88069bd67a8747cca488fc
license    : MIT
component  : programming.python
summary    : HelpDev - Extracts information about the Python environment easily
description: |
    Helping users and developers to get information about the environment to report bugs or even test your system without spending a day on it. It can get information about hardware, OS, paths, Python distribution and packages, including Qt-things.
builddeps  :
    - python-pytest
setup      : |
    sed -i "s/'pip'/'pip3'/g" helpdev/__init__.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
